# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /#about
    weight: 10

  - name: Research
    url: /#research
    weight: 20

  - name: Teaching
    url: /#teaching
    weight: 30

  - name: Publications
    url: /publications/
    weight: 40

  - name: Media
    url: /media/
    weight: 50

  - name: News
    url: /#news
    weight: 60

  - name: Life Out of the Lab
    url: /life-out-of-the-lab/
    weight: 70

  - name: Contact Me
    url: /#contact
    weight: 80
